In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Profit.csv')
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [4]:
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [5]:
df.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [6]:
df.duplicated().sum()

0

In [7]:
# Create dummy variables for the 'State' column, dropping the first category to avoid multicollinearity
states = pd.get_dummies(df['State'], drop_first=True)

# Ensure dummy variables are in 0 and 1 format
states = states.astype(int)

# Drop the original 'State' column from the dataframe
df = df.drop('State', axis=1)

# Concatenate the dummy variables to the original dataframe
df = pd.concat([df, states], axis=1)

# Display the updated dataframe
df.head()

   R&D Spend  Administration  Marketing Spend     Profit  Florida  New York
0  165349.20       136897.80        471784.10  192261.83        0         1
1  162597.70       151377.59        443898.53  191792.06        0         0
2  153441.51       101145.55        407934.54  191050.39        1         0
3  144372.41       118671.85        383199.62  182901.99        0         1
4  142107.34        91391.77        366168.42  166187.94        1         0

In [8]:
X = df[['R&D Spend','Administration','Marketing Spend','Florida','New York']]
X

    R&D Spend  Administration  Marketing Spend  Florida  New York
0   165349.20       136897.80        471784.10        0         1
1   162597.70       151377.59        443898.53        0         0
2   153441.51       101145.55        407934.54        1         0
3   144372.41       118671.85        383199.62        0         1
4   142107.34        91391.77        366168.42        1         0
5   131876.90        99814.71        362861.36        0         1
6   134615.46       147198.87        127716.82        0         0
7   130298.13       145530.06        323876.68        1         0
8   120542.52       148718.95        311613.29        0         1
9   123334.88       108679.17        304981.62        0         0
10  101913.08       110594.11        229160.95        1         0
11  100671.96        91790.61        249744.55        0         0
12   93863.75       127320.38        249839.44        1         0
13   91992.39       135495.07        252664.93        0         0
14  119943.24       156547.42        256512.92        1         0
15  114523.61       122616.84        261776.23        0         1
16   78013.11       121597.55        264346.06        0         0
17   94657.16       145077.58        282574.31        0         1
18   91749.16       114175.79        294919.57        1         0
19   86419.70       153514.11             0.00        0         1
20   76253.86       113867.30        298664.47        0         0
21   78389.47       153773.43        299737.29        0         1
22   73994.56       122782.75        303319.26        1         0
23   67532.53       105751.03        304768.73        1         0
24   77044.01        99281.34        140574.81        0         1
25   64664.71       139553.16        137962.62        0         0
26   75328.87       144135.98        134050.07        1         0
27   72107.60       127864.55        353183.81        0         1
28   66051.52       182645.56        118148.20        1         0
29   65605.48       153032.06        107138.38        0         1
30   61994.48       115641.28         91131.24        1         0
31   61136.38       152701.92         88218.23        0         1
32   63408.86       129219.61         46085.25        0         0
33   55493.95       103057.49        214634.81        1         0
34   46426.07       157693.92        210797.67        0         0
35   46014.02        85047.44        205517.64        0         1
36   28663.76       127056.21        201126.82        1         0
37   44069.95        51283.14        197029.42        0         0
38   20229.59        65947.93        185265.10        0         1
39   38558.51        82982.09        174999.30        0         0
40   28754.33       118546.05        172795.67        0         0
41   27892.92        84710.77        164470.71        1         0
42   23640.93        96189.63        148001.11        0         0
43   15505.73       127382.30         35534.17        0         1
44   22177.74       154806.14         28334.72        0         0
45    1000.23       124153.04          1903.93        0         1
46    1315.46       115816.21        297114.46        1         0
47       0.00       135426.92             0.00        0         0
48     542.05        51743.15             0.00        0         1
49       0.00       116983.80         45173.06        0         0

In [9]:
y= df[['Profit']]
y

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [11]:
linear_model = LinearRegression()
linear_model.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred = linear_model.predict(X_test)
y_pred

array([[ 74061.28471141],
       [ 46009.23798767],
       [ 99637.26360771],
       [155786.53229368],
       [127636.76349541],
       [192765.18597815],
       [ 63906.99972432],
       [ 54935.14415867],
       [ 84532.35238003],
       [109460.29711995]])

In [13]:
r2_score(y_test,y_pred)

0.9783259006628308

In [14]:
# Manual input for prediction
# For example, R&D Spend: 160000, Administration: 130000, Marketing Spend: 300000, State: Florida
manual_input = pd.DataFrame({
    'R&D Spend': [160000],
    'Administration': [130000],
    'Marketing Spend': [300000],
    'Florida': [1],  # 1 if state is Florida, else 0
    'New York': [0]  # 1 if state is New York, else 0
})

# Predict the output for the manual input
manual_pred = linear_model.predict(manual_input)
print("Predicted Profit for manual input:", manual_pred[0])

Predicted Profit for manual input: [183399.49990366]

In [15]:
# Manual input for prediction
manual_input_array = np.array([360000, 230000, 250000, 0, 1]).reshape(1, -1)

# Convert the numpy array to a DataFrame with the correct column names
manual_input = pd.DataFrame(manual_input_array, columns=['R&D Spend', 'Administration', 'Marketing Spend', 'Florida', 'New York'])

# Predict the output for the manual input
manual_pred = linear_model.predict(manual_input)
print("Predicted Profit for manual input:", manual_pred[0])

Predicted Profit for manual input: [340738.52230514]

In [16]:
# Displaying coefficients
print("Coefficients(M): ", linear_model.coef_)
print("Intercept (C): ", linear_model.intercept_)

Coefficients(M):  [[ 8.13230566e-01 -4.65775420e-02  2.69909892e-02 -1.07669797e+03
  -3.76485056e+02]]
Intercept (C):  [52317.09103701]

### Using StandardScaler Approach

In [17]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv('Profit.csv')

# Create dummy variables for the 'State' column, dropping the first category to avoid multicollinearity
states = pd.get_dummies(df['State'], drop_first=True)

# Ensure dummy variables are in 0 and 1 format
states = states.astype(int)

# Drop the original 'State' column from the dataframe
df = df.drop('State', axis=1)

# Concatenate the dummy variables to the original dataframe
df = pd.concat([df, states], axis=1)

# Define the feature set and target variable
X = df[['R&D Spend', 'Administration', 'Marketing Spend', 'Florida', 'New York']]
y = df['Profit']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Predict the output for the test set
y_pred = linear_model.predict(X_test)

print(y_pred)
r2_score(y_test,y_pred)

[ 74061.28471133  46009.2379876   99637.26360759 155786.53229373
 127636.76349538 192765.18597814  63906.99972423  54935.14415853
  84532.35238007 109460.29711993]

0.9783259006626639

In [18]:
# Manual input for prediction
manual_input = pd.DataFrame({
    'R&D Spend': [160000],
    'Administration': [130000],
    'Marketing Spend': [300000],
    'Florida': [1],  # 1 if state is Florida, else 0
    'New York': [0]  # 1 if state is New York, else 0
})

# Apply scaling to the manual input
manual_input_scaled = scaler.transform(manual_input)

# Predict the output for the scaled manual input
manual_pred = linear_model.predict(manual_input_scaled)
print("Predicted Profit for manual input:", manual_pred[0])

Predicted Profit for manual input: 183399.49990372785